/*
 * swagger test
 * swagger client sdk test.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse2001DataDataPageList model module.
 * @module model/InlineResponse2001DataDataPageList
 * @version 1.0.0
 */
export class InlineResponse2001DataDataPageList {
  /**
   * Constructs a new <code>InlineResponse2001DataDataPageList</code>.
   * @alias module:model/InlineResponse2001DataDataPageList
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2001DataDataPageList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2001DataDataPageList} obj Optional instance to populate.
   * @return {module:model/InlineResponse2001DataDataPageList} The populated <code>InlineResponse2001DataDataPageList</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2001DataDataPageList();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {String} name
 * @default 'hello mini'
 */
InlineResponse2001DataDataPageList.prototype.name = 'hello mini';

/**
 * @member {Number} id
 */
InlineResponse2001DataDataPageList.prototype.id = undefined;

