/*
 * swagger test
 * swagger client sdk test.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InlineResponse2001DataData} from './InlineResponse2001DataData';

/**
 * The InlineResponse2001Data model module.
 * @module model/InlineResponse2001Data
 * @version 1.0.0
 */
export class InlineResponse2001Data {
  /**
   * Constructs a new <code>InlineResponse2001Data</code>.
   * @alias module:model/InlineResponse2001Data
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2001Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2001Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse2001Data} The populated <code>InlineResponse2001Data</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2001Data();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('msg'))
        obj.msg = ApiClient.convertToType(data['msg'], 'String');
      if (data.hasOwnProperty('data'))
        obj.data = InlineResponse2001DataData.constructFromObject(data['data']);
    }
    return obj;
  }
}

/**
 * @member {String} status
 * @default 'success'
 */
InlineResponse2001Data.prototype.status = 'success';

/**
 * @member {String} msg
 * @default 'page list found'
 */
InlineResponse2001Data.prototype.msg = 'page list found';

/**
 * @member {module:model/InlineResponse2001DataData} data
 */
InlineResponse2001Data.prototype.data = undefined;

