/*
 * swagger test
 * swagger client sdk test.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse400Data model module.
 * @module model/InlineResponse400Data
 * @version 1.0.0
 */
export class InlineResponse400Data {
  /**
   * Constructs a new <code>InlineResponse400Data</code>.
   * @alias module:model/InlineResponse400Data
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse400Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse400Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse400Data} The populated <code>InlineResponse400Data</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse400Data();
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('msg'))
        obj.msg = ApiClient.convertToType(data['msg'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} status
 * @default 'error'
 */
InlineResponse400Data.prototype.status = 'error';

/**
 * @member {String} msg
 * @default 'invalid auth token'
 */
InlineResponse400Data.prototype.msg = 'invalid auth token';

