/*
 * swagger test
 * swagger client sdk test.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InlineResponse2001DataDataPageList} from './InlineResponse2001DataDataPageList';

/**
 * The InlineResponse2001DataData model module.
 * @module model/InlineResponse2001DataData
 * @version 1.0.0
 */
export class InlineResponse2001DataData {
  /**
   * Constructs a new <code>InlineResponse2001DataData</code>.
   * @alias module:model/InlineResponse2001DataData
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2001DataData</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2001DataData} obj Optional instance to populate.
   * @return {module:model/InlineResponse2001DataData} The populated <code>InlineResponse2001DataData</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2001DataData();
      if (data.hasOwnProperty('pageList'))
        obj.pageList = ApiClient.convertToType(data['pageList'], [InlineResponse2001DataDataPageList]);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/InlineResponse2001DataDataPageList>} pageList
 */
InlineResponse2001DataData.prototype.pageList = undefined;

