/*
 * swagger test
 * swagger client sdk test.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.26
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerTest);
  }
}(this, function(expect, SwaggerTest) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerTest.UserApi();
  });

  describe('(package)', function() {
    describe('UserApi', function() {
      describe('authGet', function() {
        it('should call authGet successfully', function(done) {
          // TODO: uncomment, update parameter values for authGet call and complete the assertions
          /*
          var opts = {};

          instance.authGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerTest.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('pageListGet', function() {
        it('should call pageListGet successfully', function(done) {
          // TODO: uncomment, update parameter values for pageListGet call and complete the assertions
          /*
          var opts = {};

          instance.pageListGet(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(SwaggerTest.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
